### PR TITLE
Activate builds

### PR DESCRIPTION
**Pull request by joshmoore**
see #2

### CODE REVIEW

**Comment by joshmoore** [comment]
@manics : any suggestions other than following https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#appveyor ?

**Comment by manics** [comment]
Does it have to be a symlink? Is that the cause of the problems on Windows?

**Comment by joshmoore** [comment]
Nah. The windows problems were just that bld.bat was missing. Now the question is how to publish the windows build.

**Comment by manics** [comment]
Could use Azure since we've already got an example? https://github.com/ome/conda-zeroc-ice36-python
Or stay native to GitHub and develop a GitHub workflow?

**Comment by joshmoore** [comment]
Re-opening to (hopefully) trigger azure.

**Pull request merged**
