### PR TITLE
BFTools 6.6.0

### PR DESCRIPTION
**Pull request by jburel**
Replaces https://github.com/ome/conda-bftools/pull/5

To test:
* create a conda environment and install bftools
* Check command from bftools like ``showinf``

To install
```
conda create --name bftools
conda activate bftools
conda install -c jburel bftools
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice! And you tagged 6.6.0 on your repo in order to make this build?

**Comment by jburel** [comment]
Yes, I pushed a 6.6.0 tag to my repo

**Review by joshmoore — APPROVED** [review]
```
$ conda create -n bftools -c jburel bftools
$ conda activate bftools
(bftools) ~ $ showinf -version
Version: 6.6.0
Build date: 14 December 2020
VCS revision: e0cdb3c28b52ba1b429d56c37a409fe53b5722ba
```

Looks good. Happy to see these be generated automatically.

Two possible follow-up points:
 * doesn't look like this is going to be overly generalizable into a template for the likes of conda-bioformats2raw/raw2ometiff
 * at the same time, I image a move to conda-forge would also be useful in order to have the automatic updates when upstream changes.

Leaving you to rollout from the main fork in case any steps like keys are necessary.

**Comment by jburel** [comment]
The secrets are in-place on openmicroscopy. I will push a tag today

**Comment by jburel** [comment]
We use the ``omerelease" as the anaconda user. This means that the package ends up on the "omerelease" channel and not the "ome" channel so that will have to be reviewed.

**Comment by jburel** [comment]
Ok that's better 
https://anaconda.org/ome/bftools

**Pull request merged**
